version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    networks:
      - webapi
    build:
      context: .
      dockerfile: ./Dockerfile

  nginx:
    image: nginx:1.21.6-alpine
    networks:
      - webapi
    ports:
      - 80:80
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  webapi: